config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'sports#index'
  resources :sports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sport.rb
class Sport < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create] 

  def index
    @sports = Sport.all
  end
  
  def new
    @sport = Sport.new
  end
  
  def create
    current_user.places.create(place_params)
    redirect_to root_path
  end

  def show
    @sport = Sport.find(params[:id])
  end
    
  def edit
    @sport = Sport.find(params[:id])
  end

  private

  def place_params
    params.require(:sport).permit(:name, :team, :city)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sports Zone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <%= link_to 'Sportszone', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_sport_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Place
            <% end %>
          </li>
        </ul>

        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>

      </div>

    </nav>  

    <% if notice.present? %>

      <p class="alert alert-info"><%= notice %></p>

    <% end %>

    <% if alert.present? %>

      <p class="alert alert-danger"><%= alert %></p>

    <% end %>

    <%= yield %>
    
  </body>
</html>

app/views/sports/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Sport</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :team %>
    <%= f.input :city %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/sports/index.html.erb

<% @sports.each do |sport| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= sport.name %></h1>
    <i><%= sport.team %></i><br /><br />
    <p><%= sport.city %></p><br />

    <% if sport.user.present? %>
      <small><%= sport.user.email %></small>
    <% end %>

  <% if sport.comments.present? %>

  <div class="col-12">
      
      <blockquote>
        <% if sport.comments.last.humanized_rating.present? %>
          <b><%= sport.comments.last.humanized_rating %></b> -
        <% end %>
        <%= sport.comments.last.message %>
        <small><%= sport.comments.last.user.email %></small>
      </blockquote>
    </div>
  <% end %>
</div>


   <% end %>
  <br />

  
  <%= will_paginate @places %>

  </div>

  <hr />
<% end %>




app/views/sports/new.html.erb
<div class="booyah-box col-10 offset-1">
<h1>Enter Your Favorite Sport</h1>
 <%= simple_form_for @sport do |f| %>
     <%= f.input :name %>
     <%= f.input :team %>
     <%= f.input :city %>
     <br />
     <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/sports/show.html.erb
<div class="booyah-box col-10 offset-1">
<h1><%= @place.name %></h1>
<i><%= @place.team %></i>
<br/><br/>
<p><%= @place.city %></p>

<br />

</div>